### ISSUE TITLE
Feature: Provide a way to exclude a namespace(s) when targeting all namespaces via the selector

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#18]

**Comment by rocktavious** [comment]
My thinking is to adjust the configuration file to allow for specifying namespaces as a list by adding a new field `namespaces`
```
service:
  import:
  - selector:
      kind: deployment
      namespaces: 
        - infra
```

which would then allow us to add another new field `namespacesRule` that accepts `include` (default if not present) or `exclude` which controls how both the `namespace` and `namespaces` fields are interpreted.

```
service:
  import:
  - selector:
      kind: deployment
      namespaces: 
      - "kube-system"
      namespacesRule: exclude
```

**Comment by rocktavious** [comment]
It was also suggested that we look for a specific annotation or label on namespaces that excludes them from being looked at.

**Comment by rocktavious** [comment]
After some design review and feedback we have adjusted the spec change to be backwards incompatible allowing you to specify which namespaces to explicitly include or exclude

```yaml
service:
  import:
  - selector:
      kind: deployment
      namespace: 
        include: // if set only these namespaces will be inspected
          - "default"
        exclude: // if set these namespaces will be excluded from inspection
          - "kube-system"
```

It is currently unclear what the intention of the above would amount to in terms what namespaces to consider since the scope is set to only look at `default` namespace but then exclude `kube-system` which wouldn't be inscope anyways.  This may be an edgecase that doesn't make sense and would be OK if it only inspected the namespaces in `include` list and the extra exclude is consider erroneous
