### ISSUE TITLE
Log file shows sync tries to add repository that already exists

### ISSUE THREAD

**Issue by lboynton** [OpsLevel/kubectl-opslevel#286]
Version: v2024.3.18

After updating to this version, we are no longer losing data :) However I've noticed the log contains this error:

```
2:49PM ERR [label-controller] Failed assigning repository '{"service":null,"repository":{"alias":"github.com:xxx/repo-name"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.
```

It looks like it's trying to set a repo when it doesn't need to?

Config is similar to the following:

```
version: "1.3.0"
service:
  import:
    - selector:
        apiVersion: apps/v1
        kind: Deployment
        excludes:
          - .metadata.namespace == "kube-system"
      opslevel:
        name: .metadata.name
        aliases:
          - '"k8s:\(.metadata.name)-\(.metadata.namespace)"'
        tags:
          assign:
            - '{"imported": "kubectl-opslevel"}'
          create:
            - '{"environment": "${environment}"}'
        repositories:
          - 'if .metadata.annotations.repository_url" then .metadata.annotations.repository_url | gsub("^git@" ; .value) | gsub ("\.git$" ; .value) else null end'
```
