### ISSUE TITLE
feature: support a version field in the configuration file to allow for making backwards incompatible changes

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#30]
```yaml
version: 1.0
service:
  import:
    ...
```

This would allow for us to first parse the file to detect the version and then parse it with the correct go struct so we can safely support backwards incompatible changes to the configuration file without breaking users.
