### ISSUE TITLE
feature: support tags that are updated and tags that are append only

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#31]
There are 2 tag API's that are there for different reasons.  We started with the tag assign API which is generally used for reconciliation as it will update the tag value if an existing tag with the same key name exists.

This is sometimes unwanted as it would be nice to have tags with the same key name but different values appended to the service.

This issue proposes a backwards incompatible change to the configuration file:

```yaml
      tags:
        assign: # tags here will be updated if the value changes
          - '{"imported": "kubectl-opslevel"}'
          - .spec.template.metadata.labels
        create: # tags here will be appended if a key with the same name but different value is found
          - .spec.template.metadata.labels.environment
```
