### ISSUE TITLE
the new create tag flow does not handle empty values

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#40]
the config is

```yaml
        tags:
          create: # tag with the same key name but with a different value with be added to the service
            - '{"environment": .spec.template.metadata.labels.environment}'
```

where the result json object is because the jq lookup did not find the field:

```json
{"environment": ""}
```

which is then sent to the OpsLevel API resulting in

```
[opslevel-sync] 4:11PM ERR ===> Failed creating tag 'environment = ' on service: 'coredns' 
[opslevel-sync] 	REASON: OpsLevel API Errors:
[opslevel-sync] 	* Value is too short (minimum is 1 character)
```
