### ISSUE TITLE
edgecase with new tag assign & create fields

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#41]
When you use the new tag configuration:

```yaml
        tags:
          assign: # tag with the same key name but with a different value will be updated on the service
            - .spec.template.metadata.labels
          create: # tag with the same key name but with a different value with be added to the service
            - '{"environment": .spec.template.metadata.labels.environment}'
```

this will cause the tag key name `environment` to show up in both lists and cause what amounts to unexpected behavior if that tag value was changed.

If you have `environment = prod` but then during a reconcile loop the value was changed to be `environment = dev` this causes both an update to the exist tag (because of the inclusion in `assign` but then also create a fully new tag because of the inclusion in `create` leaving the service with 2 tags of `environment = dev` and potentially causing problems for `assign` in the future.

The proposed solution is to remove any tag names that appear in the `create` list from appearing in the `assign` list because the intention is that you generally are not wanting to reconcile via assign a tag specifically called out in in the `create` list.

So the above configuration would remove the tag with key name `environment` from the `assign` list before reconciling.
