### ISSUE TITLE
feature: add ability to filter the resources found by using JQ expressions

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#50]
There are data collection edgecase where all resources of a specific kind in a namespace need to be excluded from being gathered for induction as services.  It would be nice to have a way to filter out these resources.  If we also implement JQ parsing of these filters so they have access to the kubernetes resource data we could then support any kind of filtering that would be desired to be more future proof.

Here is an example configuration file with a few example:
```yaml
version: "1.1.0"
service:
  import:
    - selector:
        kind: deployment
        excludes: # filters out resources if any expression returns truthy
          - .metadata.namespace == "kube-system" 
          - .metadata.annotations."opslevel.com/ignore"
          - .metadata.labels.environment == "dev"
      opslevel: # This is how you map your kubernetes data to opslevel service
        name: .metadata.name
```

The intention here is that a User could write as many filters as they need that will be run on a per resource basis that if any one of them returns truthy the resource will be skipped.

Because these filters are truthy a User could also negate the test to perform inclusion filters.  For example if a User had 3 values for the label `environment` (`dev`, `staging` and `prod`) they could use the following to filter out everything but `prod` resources.

```yaml
version: "1.1.0"
service:
  import:
    - selector:
        kind: deployment
        excludes: # filters out resources if any expression returns truthy
          - .metadata.labels.environment != "prod"
      opslevel: # This is how you map your kubernetes data to opslevel service
        name: .metadata.name
```

This could entirely replace our namespace include/exclude as well as our label selectors fields because it is both more robust and more flexible.
