### ISSUE TITLE
feature: add ability to query for custom resources (or any listable resource in k8s)

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#51]
Currently we support only a small set of kubernetes resources through a handful of key names IE `Deployment`, `ConfigMap` etc

To increase our user's ability to query any kind of resource in their kubernetes cluster we need to switch our configuration format to use something more explict as well as switch to using the dynamic client in kubernetes client-go.

The configuration changes will require that we specify an `apiVersion` alongside the `kind` so that we can properly lookup the resource in their cluster and feed the dynamic client the right `GroupVersionResource` type to query for.

```yaml
version: "1.1.0"
service:
  import:
    - selector:
        apiVersion: apps/v1
        kind: Deployment
```

This then lets us support querying for custom resources as an example the [vault-crd custom resource](https://github.com/DaspawnW/vault-crd)

```yaml
version: "1.1.0"
service:
  import:
    - selector:
        apiVersion: koudingspawn.de/v1
        kind: Vault
```

This also lets us inform the user that they can use `kubectl api-resources --verbs="get,list"` to find the information to populate the fields with.
