### ISSUE TITLE
Edgecase during "first time" service import when trying to map multiple k8s resources to 1 service

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/kubectl-opslevel#78]
A customer has reported an edge case during `service import` when trying to map multiple k8s deployments together as 1 service using the annotation `app.kubernetes.io/part-of` when none of the services exist yet.

`service preview` showed 4 distinct services with a common alias value but the `service import` end result was 1 service with the details and 2 erroneously created services.

I think this is due to the fact that we see 3 distinct service entries and then run each of those in parallel go routines.  There are a few options we can try and take to mitigate this:
- collapse the `service preview` data based on overlapping aliases (likely the best option - and would fix the `service preview` output as well)
- Issue "Service Create" in serial first skipping over duplicate services by checking if the service exists first - then move on to parallelizing the reconciliation part once we know all services have been created (likely more complex to implement under the hood)

The configuration file that was used
```
version: "1.1.0"
service:
  import:
    - selector:
        apiVersion: apps/v1
        kind: Deployment
        namespaces:
          - argocd
        excludes:
          # Only resources using Hootsuite's standardized labels are included.
          - '.metadata.labels."app.kubernetes.io/part-of" or .metadata.labels."app.kubernetes.io/name" | not'
      opslevel:
        name: '[.metadata.labels."app.kubernetes.io/part-of", .metadata.labels."app.kubernetes.io/name"] | map(select(.)) | .[0]'
        aliases:
          - '[.metadata.labels."app.kubernetes.io/part-of", .metadata.labels."app.kubernetes.io/name"] | map(select(.)) | .[0]'
          - .metadata.labels."app.kubernetes.io/name"
        tags:
          assign:
            - '{"cloud-platform": "Kubernetes"}'
```
